config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :admins
  devise_scope :admin do
    scope module: :admins, path: :admins, as: :admin do
      get 'dashboards/show', as: :root
      resources :admins
      resources :customers do
        patch 'unlock', on: :member
      end
    end
  end

  devise_for :customers, controllers: { registrations: 'customers/registrations' }
  devise_scope :customer do
    scope module: :customers, path: :customers, as: :customer do
      get 'dashboards/show', as: :root
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "home#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  normalizes :email, with: ->(email) { email.strip.downcase }
  normalizes :username, with: ->(username) { username.strip.downcase }

  validates :username,
    presence: true,
    uniqueness: { case_sensitive: true }

  validates :first_name,
    presence: true

  validates :last_name,
    presence: true

  # Include devise modules. Others available are:
  # :registerable, :recoverable, :rememberable, :confirmable, :lockable, :timeoutable, and :omniauthable
  devise(
    :database_authenticatable,
    :validatable,
    :trackable,
    authentication_keys: [:login],
    case_insensitive_keys: [:login],
    strip_whitespace_keys: [:login],
  )

  def login
    email.presence || username.presence
  end

  def self.find_for_authentication(conditions)
    login = conditions.delete(:login)
    where(email: login).or(where(username: login)).take
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  after_create :enqueue_registration_cleanup

  validates :first_name,
    presence: true

  validates :last_name,
    presence: true

  # Include devise modules. Others available are:
  # :omniauthable
  devise(
    :database_authenticatable,
    :registerable,
    :recoverable,
    :rememberable,
    :validatable,
    :confirmable,
    :lockable,
    :timeoutable,
  )

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    approved? ? super : :not_approved
  end

  private

  def enqueue_registration_cleanup
    RegistrationCleanupJob.set(wait: 1.day).perform_later(self)
  end
end

app/controllers/admins/admins_controller.rb
class Admins::AdminsController < Admins::ApplicationController
  before_action :set_admin, only: [:show, :edit, :update, :destroy]

  def index
    @admins = Admin.all.order(email: :asc)
  end

  def show
  end

  def new
    @admin = Admin.new
  end

  def edit
  end

  def create
    @admin = Admin.new(admin_create_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to admin_admin_url(@admin), notice: t(".success") }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @admin.update(admin_update_params)
        format.html { redirect_to admin_admin_url(@admin), notice: t(".success") }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @admin.destroy

    respond_to do |format|
      format.html { redirect_to admin_admins_url, notice: t(".success") }
      format.json { head :no_content }
    end
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def admin_params
    params.require(:admin).permit(
      :email,
      :username,
      :password,
      :password_confirmation,
      :first_name,
      :last_name,
      :born_on,
      :street,
      :zip_code,
      :city,
    )
  end
  alias_method :admin_create_params, :admin_params

  def admin_update_params
    result = admin_params
    if result[:password].blank?
      result.delete(:password)
      result.delete(:password_confirmation) if result[:password_confirmation].blank?
    end
    result
  end
end

app/controllers/admins/application_controller.rb
class Admins::ApplicationController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < Admins::ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy, :unlock]

  def index
    @customers = Customer.all.order(email: :asc)
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def edit
  end

  def create
    @customer = Customer.new(customer_create_params)
    @customer.skip_confirmation!

    respond_to do |format|
      if @customer.save
        format.html { redirect_to admin_customer_url(@customer), notice: t(".success") }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @customer.skip_reconfirmation!

    respond_to do |format|
      if @customer.update(customer_update_params)
        format.html { redirect_to admin_customer_url(@customer), notice: t(".success") }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to admin_customers_url, notice: t(".success") }
      format.json { head :no_content }
    end
  end

  def unlock
    @customer.unlock_access!

    respond_to do |format|
      format.html { redirect_to admin_customers_url, notice: t(".success") }
      format.json { head :no_content }
    end
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(
      :email,
      :password,
      :password_confirmation,
      :first_name,
      :last_name,
      :born_on,
      :street,
      :zip_code,
      :city,
      :approved,
      :confirmed_at,
    )
  end
  alias_method :customer_create_params, :customer_params

  def customer_update_params
    result = customer_params
    if result[:password].blank?
      result.delete(:password)
      result.delete(:password_confirmation) if result[:password_confirmation].blank?
    end
    result
  end
end

app/controllers/admins/dashboards_controller.rb
class Admins::DashboardsController < Admins::ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers/application_controller.rb
class Customers::ApplicationController < ApplicationController
  before_action :authenticate_customer!
end

app/controllers/customers/dashboards_controller.rb
class Customers::DashboardsController < Customers::ApplicationController
  def show
  end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: additional_customer_attributes)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: additional_customer_attributes)
  end

  private

  def additional_customer_attributes
    [
      :first_name,
      :last_name,
      :born_on,
      :street,
      :zip_code,
      :city,
    ]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/admins/_admin.html.erb
<%# locals: (admin:, admin_counter:, admin_iteration:) -%>
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= "#{admin.first_name} #{admin.last_name}" %></h5>
    <h6 class="card-subtitle text-muted"><%= "@#{admin.username}" %></h6>
    <p class="card-text"><%= admin.email %></p>
    <%= link_to t(".show"), admin_admin_path(admin), class: "card-link" %>
    <%= link_to t(".edit"), edit_admin_admin_path(admin), class: "card-link" %>
    <%= link_to t(".destroy"), admin_admin_path(admin), class: "card-link", data: { turbo_method: :delete, turbo_confirm: t(".confirm") } %>
  </div>
</div>

app/views/admins/admins/_form.html.erb
<%# locals: (admin:) -%>
<%= form_for [:admin, admin] do |f| %>
  <%= render "devise/shared/error_messages", resource: admin %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :password %> <i>(<%= t('devise.registrations.edit.leave_blank_if_you_don_t_want_to_change_it') %>)</i><br />
    <%= f.password_field :password %>
    <% if @minimum_password_length %>
      <br />
      <em><%= t('devise.shared.minimum_password_length', count: @minimum_password_length) %></em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :zip_code %><br />
    <%= f.text_field :zip_code %>
  </div>

  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :born_on %><br />
    <%= f.date_field :born_on %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary mt-2" %>
  </div>
<% end %>

app/views/admins/admins/edit.html.erb
<h1><%= t(".title") %></h1>

<%= render "form", admin: @admin %>

app/views/admins/admins/index.html.erb
<h1><%= t(".title") %></h1>

<%= render @admins %>

<%= link_to t(".new_admin"), new_admin_admin_path, class: "btn btn-primary mt-2" %>

app/views/admins/admins/new.html.erb
<h1><%= t(".title") %></h1>

<%= render "form", admin: @admin %>

app/views/admins/admins/show.html.erb
<h1><%= t(".title") %></h1>

<dl>
  <% @admin.attributes.each do |key, value| %>
    <dt><%= Admin.human_attribute_name(key) %></dt>
    <dd>
      <%- if value.blank? && !value.eql?(false) %>
        <%= t("admins.shared.value.blank") %>
      <%- elsif key.match?("password") || key.match?("token") %>
        <%= t("admins.shared.value.filtered") %>
      <% else %>
        <%= value %>
      <% end %>
    </dd>
  <% end %>
</dl>

app/views/admins/customers/_customer.html.erb
<%# locals: (customer:, customer_counter:, customer_iteration:) -%>
<div class="card">
  <div class="card-body">
    <h5 class="card-title">
        <%= "#{customer.first_name} #{customer.last_name}" %>
        <%- if customer.active_for_authentication? %>
          <span class="badge text-bg-success"><%= t(".state.active") %></span>
        <%- else %>
          <%- human_inactive_message = t(".state.#{customer.inactive_message}", default: nil) %>
          <%- if human_inactive_message.present? %>
            <span class="badge text-bg-danger"><%= human_inactive_message %></span>
          <% end %>
        <% end %>
      </h5>
    <p class="card-text"><%= customer.email %></p>
    <%= link_to t(".show"), admin_customer_path(customer), class: "card-link" %>
    <%= link_to t(".edit"), edit_admin_customer_path(customer), class: "card-link" %>
    <%= link_to t(".destroy"), admin_customer_path(customer), class: "card-link", data: { turbo_method: :delete, turbo_confirm: t(".confirm") } %>
    <%- if customer.access_locked? %>
      <%= link_to t(".unlock"), unlock_admin_customer_path(customer), class: "card-link", data: { turbo_method: :patch } %>
    <% end %>
  </div>
</div>

app/views/admins/customers/_form.html.erb
<%# locals: (customer:) -%>
<%= form_for [:admin, customer] do |f| %>
  <%= render "devise/shared/error_messages", resource: customer %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %> <i>(<%= t('devise.registrations.edit.leave_blank_if_you_don_t_want_to_change_it') %>)</i><br />
    <%= f.password_field :password %>
    <% if @minimum_password_length %>
      <br />
      <em><%= t('devise.shared.minimum_password_length', count: @minimum_password_length) %></em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.check_box :approved %>
    <%= f.label :approved %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :zip_code %><br />
    <%= f.text_field :zip_code %>
  </div>

  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :born_on %><br />
    <%= f.date_field :born_on %>
  </div>

  <div class="field">
    <%= f.label :confirmed_at %><br />
    <%= f.datetime_field :confirmed_at %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary mt-2" %>
  </div>
<% end %>

app/views/admins/customers/edit.html.erb
<h1><%= t(".title") %></h1>

<%= render "form", customer: @customer %>

app/views/admins/customers/index.html.erb
<h1><%= t(".title") %></h1>

<%= render @customers %>

<%= link_to t(".new_customer"), new_admin_customer_path, class: "btn btn-primary mt-2" %>

app/views/admins/customers/new.html.erb
<h1><%= t(".title") %></h1>

<%= render "form", customer: @customer %>

app/views/admins/customers/show.html.erb
<h1><%= t(".title") %></h1>

<dl>
  <% @customer.attributes.each do |key, value| %>
    <dt><%= Customer.human_attribute_name(key) %></dt>
    <dd>
      <%- if value.blank? && !value.eql?(false) %>
        <%= t("admins.shared.value.blank") %>
      <%- elsif key.match?("password") || key.match?("token") %>
        <%= t("admins.shared.value.filtered") %>
      <% else %>
        <%= value %>
      <% end %>
    </dd>
  <% end %>
</dl>

app/views/admins/dashboards/show.html.erb
<h1><%= t(".welcome") %></h1>

<%#= render "admins/shared/links" %>

app/views/admins/shared/_navigation_content.html.erb
<ul class="navbar-nav me-auto mb-2 mb-lg-0">
  <li class="nav-item">
    <%- if controller.controller_name.eql?("dashboards") %>
      <%= link_to t(".dashboard"), admin_root_path, class: "nav-link active", aria: { current: "page" } %>
    <%- else %>
      <%= link_to t(".dashboard"), admin_root_path, class: "nav-link" %>
    <% end %>
  </li>
  <li class="nav-item">
    <%- if controller.controller_name.eql?("admins") %>
      <%= link_to t(".admins"), admin_admins_path, class: "nav-link active", aria: { current: "page" } %>
    <%- else %>
      <%= link_to t(".admins"), admin_admins_path, class: "nav-link" %>
    <% end %>
  </li>
  <li class="nav-item">
    <%- if controller.controller_name.eql?("customers") %>
      <%= link_to t(".customers"), admin_customers_path, class: "nav-link active", aria: { current: "page" } %>
    <%- else %>
      <%= link_to t(".customers"), admin_customers_path, class: "nav-link" %>
    <% end %>
  </li>
</ul>


<div class="navbar-text me-2">
  <%= t(".logged_in_as", identifier: current_admin.email) %>
</div>
<%= button_to t(".logout"), destroy_admin_session_path, method: :delete, class: "btn btn-primary mt-2" %>

app/views/customers/dashboards/show.html.erb
<h1><%= t(".welcome") %></h1>

app/views/customers/shared/_navigation_content.html.erb
<ul class="navbar-nav me-auto mb-2 mb-lg-0">
  <li class="nav-item">
    <%- if controller.controller_name.eql?("dashboards") %>
      <%= link_to t(".dashboard"), customer_root_path, class: "nav-link active", aria: { current: "page" } %>
    <%- else %>
      <%= link_to t(".dashboard"), customer_root_path, class: "nav-link" %>
    <% end %>
  </li>
  <li class="nav-item">
    <%- if controller.controller_name.eql?("registrations") %>
      <%= link_to t(".registration"), edit_customer_registration_path, class: "nav-link active", aria: { current: "page" } %>
    <%- else %>
      <%= link_to t(".registration"), edit_customer_registration_path, class: "nav-link" %>
    <% end %>
  </li>
</ul>

<div class="navbar-text me-2">
  <%= t(".logged_in_as", identifier: current_customer.email) %>
</div>
<%= button_to t(".logout"), destroy_customer_session_path, method: :delete, class: "btn btn-primary mt-2" %>

app/views/home/index.html.erb
<h1>Demo App</h1>
<p>Lorem ipsum…</p>
<%= link_to t(".customers"), new_customer_session_path %><br />
<%= link_to t(".admins"), new_admin_session_path %><br />

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to t("app_name"), root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <%- if current_customer.present? %>
        <%= render "customers/shared/navigation_content" %>
      <%- elsif current_admin.present? %>
        <%= render "admins/shared/navigation_content" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t("app_name") %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= content_for?(:content) ? yield(:content) : yield %>
    </div>
  </body>
</html>